### ISSUE TITLE
[storybook] creation of component 'Quotationblock' 

### ISSUE THREAD

**Issue by ramzi-hannachi** [DominiqueBertrand/coog-fed-planning#85]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![image (2).png](https://images.zenhubusercontent.com/5dadc4fe6a7fc5000106eb18/3d14b6a3-a1fe-4a40-b1d4-20a48e596022)

![image (1x).png](https://images.zenhubusercontent.com/5dadc4fe6a7fc5000106eb18/0b8a14b2-044a-49a7-a17a-7b8e581b6b32)

**Describe alternatives you've considered**

**Additional context**

**Comment by DominiqueBertrand** [comment]
duplicate dominiquebertrand/coog-fed-planning#57
